[package]
name = "personalcapital"
version = "0.1.0"
authors = ["Kevin Darlington <kevin@outroot.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
regex = "1.1.6"
lazy_static = "1.3.0"
serde_json = "1.0.39"
cookie_store = "0.7.0"
url = "1.7.2"
log = "0.4.6"
env_logger = "0.6.1"
